@guest
<x-guest-layout>
    @include('pages.denuncias.create')
</x-guest-layout>
@else
<x-app-layout>
    @section('content')
        @include('pages.denuncias.create')
    @endsection
</x-app-layout>
@endguest
